### ISSUE TITLE
Add prop for transition duration

### ISSUE THREAD

**Issue by ianengelbrecht** [HosseinShabani/svelte-checkbox#10]
Nice checkbox. It would be great to have a prop where I could set duration of the transition/animation, in milliseconds. Users might want it to go a bit faster or slower in some cases.

**Comment by shanelaw95** [comment]
@ianengelbrecht Looks like this got added from a recent pull request. duration can be set as a prop in ms

`<Checkbox duration="400" />`

**Comment by ianengelbrecht** [comment]
Thank you!
