### ISSUE TITLE
SVG animation not completing in Safari

### ISSUE THREAD

**Issue by csell5** [HosseinShabani/svelte-checkbox#2]
First, awesome work here. Love what you built here. I recognize this issue might be on my side, but I'm not sure how to track it down further. 

In Safari the svg won't finish drawing. I am setting the size prop ( size="2.5rem" ).

![image](https://user-images.githubusercontent.com/772569/88394698-7e357b00-cd85-11ea-8923-bbb68bae51ad.png)

Any pointers would be appreciated.

**Comment by HosseinShabani** [comment]
@csell5 yes there is problem in safari , let i check it out

**Comment by csell5** [comment]
I'm happy to test when you have something.

**Comment by pixelmund** [comment]
Any progress here?

**Comment by HosseinShabani** [comment]
@csell5 @pixelmund Fix at this version on safari, thanks.

**Comment by theClarkSell** [comment]
Great @HosseinShabani! I can confirm it's working for us. Thank you for the awesome package!

~ Clark
